# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrpConfigure.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrpConfigure(object):
    def setupUi(self, FrpConfigure):
        FrpConfigure.setObjectName("FrpConfigure")
        FrpConfigure.resize(400, 291)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        FrpConfigure.setFont(font)
        self.config = QtWidgets.QPlainTextEdit(FrpConfigure)
        self.config.setGeometry(QtCore.QRect(10, 40, 381, 211))
        self.config.setDocumentTitle("")
        self.config.setPlainText("")
        self.config.setObjectName("config")
        self.label = QtWidgets.QLabel(FrpConfigure)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(FrpConfigure)
        self.label_2.setGeometry(QtCore.QRect(10, 260, 211, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.saveButton = QtWidgets.QPushButton(FrpConfigure)
        self.saveButton.setGeometry(QtCore.QRect(240, 260, 71, 23))
        self.saveButton.setObjectName("saveButton")
        self.cancelButton = QtWidgets.QPushButton(FrpConfigure)
        self.cancelButton.setGeometry(QtCore.QRect(320, 260, 71, 23))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(FrpConfigure)
        QtCore.QMetaObject.connectSlotsByName(FrpConfigure)

    def retranslateUi(self, FrpConfigure):
        _translate = QtCore.QCoreApplication.translate
        FrpConfigure.setWindowTitle(_translate("FrpConfigure", "配置 FRP 穿透"))
        self.label.setText(_translate("FrpConfigure", "请在此输入 FRP 的配置（ini）："))
        self.label_2.setText(_translate("FrpConfigure", "请确保 local_port 与启动端口一致"))
        self.saveButton.setText(_translate("FrpConfigure", "保存"))
        self.cancelButton.setText(_translate("FrpConfigure", "取消"))
