# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HotkeyConfigure.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HotkeyConfigure(object):
    def setupUi(self, HotkeyConfigure):
        HotkeyConfigure.setObjectName("HotkeyConfigure")
        HotkeyConfigure.resize(260, 101)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        HotkeyConfigure.setFont(font)
        self.switchPeekStatusLabel = QtWidgets.QLabel(HotkeyConfigure)
        self.switchPeekStatusLabel.setGeometry(QtCore.QRect(10, 40, 81, 16))
        self.switchPeekStatusLabel.setObjectName("switchPeekStatusLabel")
        self.saveButton = QtWidgets.QPushButton(HotkeyConfigure)
        self.saveButton.setGeometry(QtCore.QRect(100, 70, 71, 23))
        self.saveButton.setObjectName("saveButton")
        self.cancelButton = QtWidgets.QPushButton(HotkeyConfigure)
        self.cancelButton.setGeometry(QtCore.QRect(180, 70, 71, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.switchPeekStatus = QtWidgets.QLineEdit(HotkeyConfigure)
        self.switchPeekStatus.setGeometry(QtCore.QRect(140, 40, 113, 20))
        self.switchPeekStatus.setObjectName("switchPeekStatus")
        self.hotkeyCheckBox = QtWidgets.QCheckBox(HotkeyConfigure)
        self.hotkeyCheckBox.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.hotkeyCheckBox.setObjectName("hotkeyCheckBox")

        self.retranslateUi(HotkeyConfigure)
        QtCore.QMetaObject.connectSlotsByName(HotkeyConfigure)

    def retranslateUi(self, HotkeyConfigure):
        _translate = QtCore.QCoreApplication.translate
        HotkeyConfigure.setWindowTitle(_translate("HotkeyConfigure", "配置快捷键"))
        self.switchPeekStatusLabel.setText(_translate("HotkeyConfigure", "切换监控状态"))
        self.saveButton.setText(_translate("HotkeyConfigure", "保存"))
        self.cancelButton.setText(_translate("HotkeyConfigure", "取消"))
        self.switchPeekStatus.setInputMask(_translate("HotkeyConfigure", "Ctrl+Alt+Q"))
        self.switchPeekStatus.setText(_translate("HotkeyConfigure", "Ctrl+Alt+Q"))
        self.hotkeyCheckBox.setText(_translate("HotkeyConfigure", "全局快捷键"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HotkeyConfigure = QtWidgets.QDialog()
    ui = Ui_HotkeyConfigure()
    ui.setupUi(HotkeyConfigure)
    HotkeyConfigure.show()
    sys.exit(app.exec_())
